language: python
python: 2.7
sudo: true
install: pip install .
script: python setup.py test
deploy:
  - provider: releases
    api_key:
      secure: Zwoz1wE2LVOwpvSc8oiy1ZXc/pUSIioab2bp4s5Z7/ZPlzM0mXv6q2ehs48k+W+EGE8h23lHDqt9aIi+gCo8gC2oFbgoKaUJ/jRTWTM28WK+qhEu0xA1qohnmBd73BbTO3F2uV8+YIjIvQPNzZ7LtoD9VJTsfqnvQe2eJSWOBVClVekBXq+Bh37/NUM1NNArgnhc2QoK/ZbVG7HVAotOGhYdBuSN3u+eRTM2ybxx8w7m72uMBp+K5XjhKmyD1/3IbDYiENddG3P+HS+iiizgUGHUpJOp44PYSdLm9XhUHZhBdzm8RibpN4xmrNmXZfDg5sXsUjLwCU8BJTHoSjgNtEm6S9SthEQxtNuMDLDlAXabnAwA/hGpxxsAodrX65DITp24kdle9A1eZkKT6uR/M8OojwB+ntoREsR9B8UVCA8j9Oq3w09c0Cd2S4BXMtdWDefzACB8zqEURK8gpsBVH5R70AHAJzMGfo9RVg8UTgxvDOcAxwK0gPfniSkDp4CoNWZ0QDSNo3j4TQjEUEtR/fSiObnLXkKFJrgDwFyeLpJxnOTklPIsHcKYXV9TFpaEarno9VhVNtjdBcjnGQa3Y1Tjjcx8widEMkqDAG70C3ppxvmYDJMXSooZY3lbBMRt9gNmsnv650umGP7MucqPVj0lhNpareBA6FIxafEtBBY=
    on:
      repo: deep-compute/nsq-api
      branch: master

  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "QJAtxE4U5Lt/YDjpmvSz8vb/i49CJktKYc4aVoEmHMlTUuquNLPzFd5r9VzkKkY9EocvZ9k/crnboqji9eIoraRjCQUPQVk6YhRA+nggJY1ZkeImrgNw9RCjNSGWoulW0nMjuHz/x1jKnEvaCI/dFndv9ap/QdUfRfwVsXSEIzyVEwxowYCyiJEYKRBNP5xqQxyfV1AdOM8Z7hWiBL0LYSt0XHpjVgdy44ZYnRkH+DilqpTDqp9dUGWHukxqwxiN7RsFnBZU4m/zdYrj6HyG8RegfP+EpirrPRsz6ECrBjngtehrvcZdvP9t0txEEOsYahrW71B23uj2VR+Xwx6M1STk8KKAQfnB2y3yzJEqQMejIQ0HIZ4YIKk/tdD7ktBUyJ9NN9AK0/hVAhrSlXAdCH9QpfZ7019fM0r3GJi/z3TWDFBjuyiKWrRjijdO2nvfKfgVKjWbX+sUALt/6JOzHOGIaXCqzpkyrVAiWzxDqewauzfaaYhxlQmzfFomJeYrIdsCggp8cZm2DaMqIGNqAlc/GXwUnWXA+Plh+1zyzDBDwnuLx+QzFWD99M5ipCPnsrHAkavDEZ4R2k66M/WBXVMqp0oPGj7KhI6DjfyWNV+rp4JIKRJDsWf+j+cY3LM4Hgo8pt1UfQSuoVniAD5MnqcEnn2S+wuEgDpVk14Q/dc="
    on:
      branch: master
      tags: true
