language: python
python: 2.7
sudo: true
install: pip install .
script: python setup.py test
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
        secure: nvbjwR/MJK42rR1vErFzNC7O9Od7Kuwb3NbbvYooIB6ZDqh0qVHPNgsV12AAExWtfmIfJcyYHqbG3UUUth1ke3BtqWg44pDKu5df0wsT7/LZH0n+vtYCKyHdRGwjrGElZ5wMy+S3o1d3fO7bTZhnbbY/U/L8aPgoIFUafTLia1JCePEmFRwpRBI1l9hDdH9exLGz5Nkzi+l5LNRwisnmsdcnR31XmFArQ/wqPi5DazRvEzAqN3tyEH4U0av4JneM2ROoUSB2AhYBYUVdMWUUSrR/tR4QlOaUPFS9qSXrV3hxEPTVuxbWg3bLnAX4U2MvGCsKf8b+gKruSdN9RDtTgwh+ul99TSEVX/9aqr12g4R4UGM1d05uU337Ror0Sc1prlauKBPsmYLSXmVVKNeeKUAJQYXjWnvJPhNdYoDqCJJRrvpUtqRWcua+Ka8O1yzUakGhe95grjI8FL0eYR5f2laffPm4bnP8Ok0HMQal18WZvu7h9Y8IsUHynipS6AFcjYuxl3U3mgXgF0Mo8c4RK2DqQI6EIVTXFxmOpgXAyV3DLn1M3GyY0l5BR77fGWlr5hl9sXJyv9zYk8Iup9HXaHFAYjftak4iNj0DnyJqI08Srq433GzN6d+d4oyelGCondiRZr3uv582JgUclwMl3jyEKeyArcrUeOri4Hk8vJo=
    name: nsq-api-0.0.1
    tag_name: 0.0.1
    on:
      repo: deep-compute/nsq-api
      branch: master

  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    user: "deepcompute"
    password:
      secure: "QJAtxE4U5Lt/YDjpmvSz8vb/i49CJktKYc4aVoEmHMlTUuquNLPzFd5r9VzkKkY9EocvZ9k/crnboqji9eIoraRjCQUPQVk6YhRA+nggJY1ZkeImrgNw9RCjNSGWoulW0nMjuHz/x1jKnEvaCI/dFndv9ap/QdUfRfwVsXSEIzyVEwxowYCyiJEYKRBNP5xqQxyfV1AdOM8Z7hWiBL0LYSt0XHpjVgdy44ZYnRkH+DilqpTDqp9dUGWHukxqwxiN7RsFnBZU4m/zdYrj6HyG8RegfP+EpirrPRsz6ECrBjngtehrvcZdvP9t0txEEOsYahrW71B23uj2VR+Xwx6M1STk8KKAQfnB2y3yzJEqQMejIQ0HIZ4YIKk/tdD7ktBUyJ9NN9AK0/hVAhrSlXAdCH9QpfZ7019fM0r3GJi/z3TWDFBjuyiKWrRjijdO2nvfKfgVKjWbX+sUALt/6JOzHOGIaXCqzpkyrVAiWzxDqewauzfaaYhxlQmzfFomJeYrIdsCggp8cZm2DaMqIGNqAlc/GXwUnWXA+Plh+1zyzDBDwnuLx+QzFWD99M5ipCPnsrHAkavDEZ4R2k66M/WBXVMqp0oPGj7KhI6DjfyWNV+rp4JIKRJDsWf+j+cY3LM4Hgo8pt1UfQSuoVniAD5MnqcEnn2S+wuEgDpVk14Q/dc="
    on:
      branch: master
      tags: true
